 //////////////////////////////////////////////////////////////////////////////
 // Project:  Aurora 64B/66B
 // Company:  Xilinx
 //
 //
 //
 // (c) Copyright 2008 - 2009 Xilinx, Inc. All rights reserved.
 //
 // This file contains confidential and proprietary information
 // of Xilinx, Inc. and is protected under U.S. and
 // international copyright and other intellectual property
 // laws.
 //
 // DISCLAIMER
 // This disclaimer is not a license and does not grant any
 // rights to the materials distributed herewith. Except as
 // otherwise provided in a valid license issued to you by
 // Xilinx, and to the maximum extent permitted by applicable
 // law: (1) THESE MATERIALS ARE MADE AVAILABLE "AS IS" AND
 // WITH ALL FAULTS, AND XILINX HEREBY DISCLAIMS ALL WARRANTIES
 // AND CONDITIONS, EXPRESS, IMPLIED, OR STATUTORY, INCLUDING
 // BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, NON-
 // INFRINGEMENT, OR FITNESS FOR ANY PARTICULAR PURPOSE; and
 // (2) Xilinx shall not be liable (whether in contract or tort,
 // including negligence, or under any other theory of
 // liability) for any loss or damage of any kind or nature
 // related to, arising under or in connection with these
 // materials, including for any direct, or any indirect,
 // special, incidental, or consequential loss or damage
 // (including loss of data, profits, goodwill, or any type of
 // loss or damage suffered as a result of any action brought
 // by a third party) even if such damage or loss was
 // reasonably foreseeable or Xilinx had been advised of the
 // possibility of the same.
 //
 // CRITICAL APPLICATIONS
 // Xilinx products are not designed or intended to be fail-
 // safe, or for use in any application requiring fail-safe
 // performance, such as life-support or safety devices or
 // systems, Class III medical devices, nuclear facilities,
 // applications related to the deployment of airbags, or any
 // other applications that could lead to death, personal
 // injury, or severe property or environmental damage
 // (individually and collectively, "Critical
 // Applications"). Customer assumes the sole risk and
 // liability of any use of Xilinx products in Critical
 // Applications, subject only to applicable laws and
 // regulations governing limitations on product liability.
 //
 // THIS COPYRIGHT NOTICE AND DISCLAIMER MUST BE RETAINED AS
 // PART OF THIS FILE AT ALL TIMES.
 
 //
 //////////////////////////////////////////////////////////////////////////////
 //
 //  FRAME CHECK
 //
 //
 //
 //  Description: This module is a  pattern checker to test the Aurora
 //               designs in hardware. The frames generated by FRAME_GEN
 //               pass through the Aurora channel and arrive at the frame checker 
 //               through the RX User interface. Every time an error is found in
 //               the data recieved, the error count is incremented until it 
 //               reaches its max value.
 //////////////////////////////////////////////////////////////////////////////
 
 `timescale 1 ns / 10 ps
 `define DLY #1
 
(* DowngradeIPIdentifiedWarnings="yes" *)
 module aurora_64b66b_0_FRAME_CHECK
 (
     // User Interface
     RX_D,  
     RX_REM,
     RX_SOF_N,
     RX_EOF_N,
     RX_SRC_RDY_N,  
     DATA_ERR_COUNT,
     RX_FRAME_CNT,
 
 
     // System Interface
     CHANNEL_UP,
     USER_CLK,       
     RESET
   
 ); 
 //*********************** Parameter Declarations************************
     parameter            AURORA_LANES    = 1;
     parameter            LANE_DATA_WIDTH = (AURORA_LANES*64);
     parameter            REM_BUS         = 3;
     parameter            DATA_WIDTH      = 8;
     
     parameter [0:63] FIXED_DATA_A = 64'h5555_5555_5555_5555;
     parameter [0:63] FIXED_DATA_B = 64'hAAAA_AAAA_AAAA_AAAA;     
     //parameter [0:63] FIXED_DATA = 64'h5555_5555_5555_5555; // 期望的固定数�?? // 固定发�?�数�??     
 
 //***********************************Port Declarations*******************************
     //PDU Interface
     input     [0:LANE_DATA_WIDTH-1]    RX_D;
     input     [0:REM_BUS-1]            RX_REM;
     input                              RX_SOF_N; 
     input                              RX_EOF_N; 
     input                              RX_SRC_RDY_N; 
     
     //System Interface
     input                              CHANNEL_UP; 
     input                              USER_CLK; 
     input                              RESET;  
     output    [0:DATA_WIDTH-1]         DATA_ERR_COUNT;
     output     [31:0]                  RX_FRAME_CNT;
 
 //***************************Internal Register Declarations*************************** 
 
     //PDU interface signals
     reg       [0:DATA_WIDTH-1]         DATA_ERR_COUNT; 
 
     wire                               reset_i; 
     wire                               RESET_ii; 



 //*********************************Main Body of Code**********************************
 
   assign reset_i = RESET || (!CHANNEL_UP);
   assign resetUFC = reset_i; 

    assign RESET_ii = RESET ; 

  /*****************************PDU Data Genetration & Checking**********************/


    // 打拍寄存器（可�?�，用于对齐时序�??
    reg [0:63]     RX_D_R;
    reg [0:2]      RX_REM_R;
    reg            RX_EOF_N_R;
    reg            RX_SRC_RDY_N_R;

    always @(posedge USER_CLK) begin
        RX_D_R          <= #1 RX_D;
        RX_REM_R        <= #1 RX_REM;
        RX_SRC_RDY_N_R  <= #1 RX_SRC_RDY_N;
        RX_EOF_N_R      <= #1 RX_EOF_N;
    end

    // 数据有效标志（打拍后�??
    wire data_valid = !RX_SRC_RDY_N_R;

    // ����������ֵѡ��Ĵ���?
    reg exp_frame_type, next_exp_frame_type;
    reg [0:63] expected_data;   // ��ǰ����ֵ

    // ��ʱ���߼��и��� exp_frame_type
    always @(posedge USER_CLK) begin
        if (reset_i) begin
            exp_frame_type <= 1'b0;
        end else begin
            exp_frame_type <= next_exp_frame_type;
        end
    end

    // 定义帧结束检测信号（已在模块中使用）
    wire eof_detected = !RX_EOF_N_R && !RX_SRC_RDY_N_R; // ���ն˾����� EOF ��Ч

    always @* begin
        next_exp_frame_type = exp_frame_type;
        if (eof_detected) begin
            next_exp_frame_type = ~exp_frame_type;
        end
    end

    // ���� exp_frame_type ѡ������ֵ
    always @* begin
        expected_data = (exp_frame_type == 1'b0) ? FIXED_DATA_A : FIXED_DATA_B;
    end


    // 根据 RX_REM 对齐接收数据和期望数�??
    reg [0:63] aligned_rx, aligned_exp;

    always @* begin
        aligned_exp = 64'b0;
        case (RX_REM_R)
            3'd0: begin  aligned_exp = {expected_data[0:7],   56'b0}; end
            3'd1: begin  aligned_exp = {expected_data[0:15],  48'b0}; end
            3'd2: begin  aligned_exp = {expected_data[0:23],  40'b0}; end
            3'd3: begin  aligned_exp = {expected_data[0:31],  32'b0}; end
            3'd4: begin  aligned_exp = {expected_data[0:39],  24'b0}; end
            3'd5: begin  aligned_exp = {expected_data[0:47],  16'b0}; end
            3'd6: begin  aligned_exp = {expected_data[0:55],   8'b0}; end
            3'd7: begin aligned_exp = expected_data;                end
            default: begin   aligned_exp = expected_data;              end
        endcase
    end

    always @* begin
        aligned_rx = 64'b0;
        case (RX_REM_R)
            3'd0: begin aligned_rx = {RX_D_R[0:7],   56'b0};  end
            3'd1: begin aligned_rx = {RX_D_R[0:15],  48'b0};  end
            3'd2: begin aligned_rx = {RX_D_R[0:23],  40'b0};  end
            3'd3: begin aligned_rx = {RX_D_R[0:31],  32'b0};  end
            3'd4: begin aligned_rx = {RX_D_R[0:39],  24'b0};  end
            3'd5: begin aligned_rx = {RX_D_R[0:47],  16'b0};  end
            3'd6: begin aligned_rx = {RX_D_R[0:55],   8'b0};  end
            3'd7: begin aligned_rx = RX_D_R;                  end
            default: begin aligned_rx = RX_D_R;              end
        endcase
    end
    
    wire data_err = data_valid && (aligned_rx != aligned_exp);     
 
     //Compare the incoming PDU data with calculated expected PDU data.
     //Increment the PDU ERR COUNTER if mismatch occurs
     //Stop the PDU ERR COUNTER once it reaches its max value
     always @ (posedge USER_CLK)
     begin	       
       if(RESET_ii)
         DATA_ERR_COUNT <= `DLY 8'b0;
       else if(!CHANNEL_UP)
         DATA_ERR_COUNT <= `DLY 8'b0;
       else if(&DATA_ERR_COUNT)
         DATA_ERR_COUNT <= `DLY DATA_ERR_COUNT;
       else if(data_err)
         DATA_ERR_COUNT <= `DLY DATA_ERR_COUNT + 1; 
       end 

    // 在模块内部声明寄存器
    reg [31:0] rx_frame_cnt;


    // 在时序�?�辑中增加计�?
    always @(posedge USER_CLK) begin
        if (reset_i) begin
            rx_frame_cnt <= 32'd0;
        end else if (eof_detected) begin
            rx_frame_cnt <= rx_frame_cnt + 1'b1;
        end
    end

    assign RX_FRAME_CNT = rx_frame_cnt;




       
 
 endmodule           
