 ///////////////////////////////////////////////////////////////////////////////
 // Project:  Aurora 64B/66B
 // Company:  Xilinx  
 //
 //
 // (c) Copyright 2008 - 2009 Xilinx, Inc. All rights reserved.
 //
 // This file contains confidential and proprietary information
 // of Xilinx, Inc. and is protected under U.S. and
 // international copyright and other intellectual property
 // laws.
 //
 // DISCLAIMER
 // This disclaimer is not a license and does not grant any
 // rights to the materials distributed herewith. Except as
 // otherwise provided in a valid license issued to you by
 // Xilinx, and to the maximum extent permitted by applicable
 // law: (1) THESE MATERIALS ARE MADE AVAILABLE "AS IS" AND
 // WITH ALL FAULTS, AND XILINX HEREBY DISCLAIMS ALL WARRANTIES
 // AND CONDITIONS, EXPRESS, IMPLIED, OR STATUTORY, INCLUDING
 // BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, NON-
 // INFRINGEMENT, OR FITNESS FOR ANY PARTICULAR PURPOSE; and
 // (2) Xilinx shall not be liable (whether in contract or tort,
 // including negligence, or under any other theory of
 // liability) for any loss or damage of any kind or nature
 // related to, arising under or in connection with these
 // materials, including for any direct, or any indirect,
 // special, incidental, or consequential loss or damage
 // (including loss of data, profits, goodwill, or any type of
 // loss or damage suffered as a result of any action brought
 // by a third party) even if such damage or loss was
 // reasonably foreseeable or Xilinx had been advised of the
 // possibility of the same.
 //
 // CRITICAL APPLICATIONS
 // Xilinx products are not designed or intended to be fail-
 // safe, or for use in any application requiring fail-safe
 // performance, such as life-support or safety devices or
 // systems, Class III medical devices, nuclear facilities,
 // applications related to the deployment of airbags, or any
 // other applications that could lead to death, personal
 // injury, or severe property or environmental damage
 // (individually and collectively, "Critical
 // Applications"). Customer assumes the sole risk and
 // liability of any use of Xilinx products in Critical
 // Applications, subject only to applicable laws and
 // regulations governing limitations on product liability.
 //
 // THIS COPYRIGHT NOTICE AND DISCLAIMER MUST BE RETAINED AS
 // PART OF THIS FILE AT ALL TIMES.
 
 //
 ////////////////////////////////////////////////////////////////////////////////
 //
 // Module TX_CRC
 // Generated by Xilinx Aurora 64B66B
 `timescale 1 ns/1 ps

 `define DLY #1
(* DowngradeIPIdentifiedWarnings="yes" *) 
 
 //***********************************Entity Declaration*******************************
 module aurora_64b66b_0_tx_crc_axi (
   s_axi_tx_tdata_ds,
   s_axi_tx_tvalid_ds,
   s_axi_tx_tready_ds,
   s_axi_tx_tkeep_ds,
   s_axi_tx_tlast_ds,
   s_axi_tx_tdata_us,
   s_axi_tx_tvalid_us,
   s_axi_tx_tready_us,
   s_axi_tx_tkeep_us,
   s_axi_tx_tlast_us,
   reset,
   channel_up,
   user_clk
 );
 
 parameter CRC_INIT  = 32'hFFFFFFFF;
 parameter DATA_WIDTH = 64;
 parameter REM_WIDTH  = 3;
 parameter STRB_WIDTH = 8;
   //--*_DS refers to output signals from the block--//
   //--*_US refers to input signals to the block--//
   output [0:(DATA_WIDTH-1)]   s_axi_tx_tdata_ds;
   output [0:7]    s_axi_tx_tkeep_ds; 
   output      	  s_axi_tx_tlast_ds;
   output      	  s_axi_tx_tvalid_ds;
   input       	  s_axi_tx_tready_ds;
   output      	  s_axi_tx_tready_us;
   input [0:(DATA_WIDTH-1)]    s_axi_tx_tdata_us;
   input [0:7]     s_axi_tx_tkeep_us; 
   input       	  s_axi_tx_tlast_us;
   input       	  s_axi_tx_tvalid_us;
   input       	  reset;
   input       	  channel_up;
   input       	  user_clk;
   
   reg [0:(DATA_WIDTH-1)]    s_axi_tx_tdata_ds;
   reg [0:7]     s_axi_tx_tkeep_ds; 
   reg       	s_axi_tx_tlast_ds;
   reg       	s_axi_tx_tvalid_ds;
   
   //__Signal declaration for one-hot encoded FSM__//
   reg   idle_r;   //--Idle or power on state
   reg   sc_frame_r; //--single cycle frame state
   reg   sof_sc_r; //--sof state for single cycle frame when TKEEP > 15
   reg   eof_sc_r; //--eof state for single cycle frame when TKEEP > 15 
   reg   sof_eof_r;  //--sof-eof state for single cycle frame when TKEEP < 16
   reg   wait_r;   //--wait state
   reg   sof_ds_r; //-build sof state for non-single cycle frames
   reg   src_not_rdy_r;  //--state for input src not rdy
   reg   data_r;   //--data state
   reg   eof_ds_r; //--build eof state
   reg   crc_r;    //--append crc state for TKEEP > 15
   
   wire  idle_c;
   wire  sc_frame_c;
   wire  sof_sc_c;
   wire  eof_sc_c;
   wire  sof_eof_c;
   wire  wait_c;
   wire  sof_ds_c;
   wire  src_not_rdy_c;
   wire  data_c;
   wire  eof_ds_c;
   wire  crc_c;
   wire [0:7]     s_axi_tx_tkeep_us_i; 
   
   //__internal register declaration__//
   reg [0:7]  tkeep_in = 8'b0;   //--store input tkeep
   reg [0:7]  tkeep_out = 8'b0;  //--build output tkeep
   reg     		s_axi_tx_tlast_us_r = 1'b0; //--TLAST delayed by one cycle
   reg [1:0] 	count;    //--count to deassert s_axi_tx_tready_us after receiving TLAST
   reg [0:(DATA_WIDTH-1)]  	s_axi_tx_tdata_us_r = 64'b0;  //--data input pipeline-I
   reg [0:(DATA_WIDTH-1)]  	s_axi_tx_tdata_us_r2 = 64'b0; //--data input pipeine-II
   reg [0:(DATA_WIDTH/2 - 1)]  	CRC_reg={DATA_WIDTH/2{1'b0}};    //--CRC output registered from CRC block
   
   //__internal wire declaration__//
   wire    		s_axi_tx_tready_us_i;
   wire    		axi4s_last_rdy_valid;   // AXI-4 Stream handshake valid
   wire    		axi4s_rdy_valid;   // AXI-4 Stream handshake valid
   wire    		CRC_DATAVALID1;  
   wire [0:31] CRC1;      //__CRC calculated
   wire [0:7]  CRC_DATAWIDTH1;  //__CRC datawidth
   wire [0:63] CRC_DATA1;   //__data input to CRC block
   wire [0:(DATA_WIDTH/2 - 1)] 	final_CRC; 
   wire    		CRC_RST;    //__reset to CRC block
   wire    		reset_crc_block;  
   //SOF generation signals  
   wire        s_axi_tx_tsof_us;
   wire        new_pkt; 
   reg         new_pkt_r=1'd0;
  
   //____________Main code begins here________________//
//--tkeep to rem conversion logic--{
reg [(REM_WIDTH-1):0]  rem_in;
reg [(STRB_WIDTH-1):0] i;
reg found_rem = 1'b0;

always @(found_rem or tkeep_in)
begin
    found_rem = 1'b0;
    rem_in = {(STRB_WIDTH-1){1'b0}};
    for(i = 0;i < STRB_WIDTH; i = i + 1)
    begin
        if ((tkeep_in[i] == 1'b0) && (found_rem == 1'b0))
        begin
            rem_in = i;
            found_rem = 1'b1;
        end
    end
end
//--tkeep to rem conversion logic--}

  assign reset_crc_block = reset || !channel_up;

  // TKEEP all 0 condition handling
  assign s_axi_tx_tkeep_us_i = !(|s_axi_tx_tkeep_us)?{8{1'b1}} :s_axi_tx_tkeep_us;

  
  //SOF generation
  assign new_pkt           = ( s_axi_tx_tvalid_us && s_axi_tx_tready_us && s_axi_tx_tlast_us  && channel_up) ? 1'b0 : ((s_axi_tx_tvalid_us && s_axi_tx_tready_us && !s_axi_tx_tlast_us && channel_up) ? 1'b1 : new_pkt_r);
  assign s_axi_tx_tsof_us  = ( ( s_axi_tx_tvalid_us && s_axi_tx_tready_us && s_axi_tx_tlast_us && channel_up) ? ((new_pkt_r) ? 1'b0 : 1'b1) : (new_pkt && (!new_pkt_r)));
 
 always @ (posedge user_clk)
 begin
   if(reset_crc_block)
     new_pkt_r <= `DLY 1'b0; //DEBUG
   else
     new_pkt_r <= `DLY new_pkt;
 end
 
     //__Initialization & state assignment for FSM__//
   always @(posedge user_clk)
     if (reset_crc_block)
     begin
       idle_r      	<= `DLY 1'b1;
       sc_frame_r    <= `DLY 1'b0;
       sof_sc_r    	<= `DLY 1'b0;
       eof_sc_r    	<= `DLY 1'b0;
       sof_eof_r   	<= `DLY 1'b0;
       wait_r      	<= `DLY 1'b0;
       src_not_rdy_r <= `DLY 1'b0;
       sof_ds_r    	<= `DLY 1'b0;
       data_r      	<= `DLY 1'b0;
       eof_ds_r    	<= `DLY 1'b0;
       crc_r     	   <= `DLY 1'b0;
     end
     else if (s_axi_tx_tready_ds)
     begin
       idle_r      	<= `DLY idle_c;
       sc_frame_r    <= `DLY sc_frame_c;
       sof_sc_r    	<= `DLY sof_sc_c;
       eof_sc_r    	<= `DLY eof_sc_c;
       sof_eof_r   	<= `DLY sof_eof_c;
       wait_r      	<= `DLY wait_c;
       src_not_rdy_r <= `DLY src_not_rdy_c;
       sof_ds_r    	<= `DLY sof_ds_c;
       data_r      	<= `DLY data_c;
       eof_ds_r    	<= `DLY eof_ds_c;
       crc_r     	   <= `DLY crc_c;
     end
     
     //__Combinatorial logic for FSM__//
     
     //--stay in idle when not receiving any frames and
     //when current frame transmission is complete --//
   assign idle_c = (idle_r & (!s_axi_tx_tsof_us || !axi4s_rdy_valid)) ||
           ((eof_ds_r || eof_sc_r || sof_eof_r) & (!s_axi_tx_tsof_us || !axi4s_rdy_valid));
     //--reach this state when input is a single cycle frame
   assign sc_frame_c = ((idle_r || eof_sc_r || sof_eof_r || eof_ds_r) & 
                   s_axi_tx_tsof_us & s_axi_tx_tlast_us & axi4s_rdy_valid);
     //--reach this state when input is single cycle frame and TKEEP < 16 so that
     //output is also a single cycle frame--//
   assign sof_eof_c  = sc_frame_r & (tkeep_in[4] == 1'b0);
     //--reach this state when input is single cycle frame and TKEEP > 15 so that
     //output is a two cycle frame--//
   assign sof_sc_c   = sc_frame_r & (tkeep_in[4] == 1'b1);
     //--reach this state to build eof for the output two cycle frame--//
   assign eof_sc_c   =   sof_sc_r;
     //--reach this state when input is not single cycle frame and sof is asserted--//
   assign wait_c   = ((idle_r || eof_sc_r || sof_eof_r || eof_ds_r) & 
                   s_axi_tx_tsof_us & !s_axi_tx_tlast_us & axi4s_rdy_valid) || (wait_r & !axi4s_rdy_valid);
     //--this state builds the output SOF --//
   assign sof_ds_c   = wait_r & axi4s_rdy_valid;
     //--reach here when src-rdy is deasserted in between a frame transmission--//
   assign src_not_rdy_c  = ((sof_ds_r || data_r) & !s_axi_tx_tvalid_us & !s_axi_tx_tlast_us_r) ||
                   (src_not_rdy_r & !s_axi_tx_tvalid_us); 
     //--this is data state for frames--//
   assign data_c   = (sof_ds_r & !s_axi_tx_tlast_us_r) ||
                 (data_r & !s_axi_tx_tlast_us_r & s_axi_tx_tvalid_us) || 
           (src_not_rdy_r & s_axi_tx_tvalid_us & !s_axi_tx_tlast_us_r);
     //--this is for adding extra cycle to insert CRC when input TKEEP > 15--//
   assign crc_c    = ((sof_ds_r || data_r || (src_not_rdy_r & s_axi_tx_tvalid_us))
                  & (s_axi_tx_tlast_us_r) & (tkeep_in[4] == 1'b1));
     //--this is for eof buildup, also reached when input TKEEP < 16--//        
   assign eof_ds_c   = ((sof_ds_r || data_r || (src_not_rdy_r & s_axi_tx_tvalid_us)) & (s_axi_tx_tlast_us_r) & (tkeep_in[4] == 1'b0)) ||
               crc_r;
               
     //__Store TKEEP value and build output TKEEP__//
   always @(posedge user_clk)
     if (axi4s_last_rdy_valid)
     begin
       tkeep_in  <= `DLY s_axi_tx_tkeep_us_i;     //--input TKEEP storage
       tkeep_out <= `DLY (s_axi_tx_tkeep_us_i[4] ? {s_axi_tx_tkeep_us_i[4:7],4'h0} : {{4{1'b1}},{s_axi_tx_tkeep_us_i[0:3]}});  //--output TKEEP is input TKEEP + 8'hFF per lane
     end
   
     //__input signals registered__//  
   always @(posedge user_clk)
   if (axi4s_rdy_valid)
   begin
     s_axi_tx_tlast_us_r  <= `DLY s_axi_tx_tlast_us;
     s_axi_tx_tdata_us_r  <= `DLY s_axi_tx_tdata_us;  //--data pipe-I
   end
 
   always @(posedge user_clk)
   begin
   if (s_axi_tx_tready_ds)
       s_axi_tx_tdata_us_r2  <= `DLY s_axi_tx_tdata_us_r;    //--data pipe-II
   end
   
     //--deassert dst-rdy-us after TLAST reception or when dst-rdy-ds is deasserted--//    
   assign s_axi_tx_tready_us   = s_axi_tx_tready_us_i;
   assign s_axi_tx_tready_us_i = (s_axi_tx_tready_ds && (count == 2'b00) && channel_up); //DEBUG 
   
     //__deassert dst_rdy_n_us for 2 cycles after eof_n_us reception
       // to take care of crc insertion in DS-data__//
   always @(posedge user_clk)
     if (reset_crc_block)
       count <= `DLY 2'b00;
     else if (axi4s_last_rdy_valid)
       count <= `DLY 2'b10;  //--count 2 cycles explicitly when dst is ready__//
     else if (|count && s_axi_tx_tready_ds)
       count <= `DLY count >> 1;
     //--Axi-4 Stream handshake valid indicator--//
   assign axi4s_rdy_valid = s_axi_tx_tvalid_us & s_axi_tx_tready_us_i;
   assign axi4s_last_rdy_valid = s_axi_tx_tlast_us & s_axi_tx_tvalid_us & s_axi_tx_tready_us_i;
     
     //__CRC block instantiation__//
 
aurora_64b66b_0_CRC_TOP #(
         .CRC_INIT(CRC_INIT)
         ) tx_crc_gen_i1 (
             .CRCRESET(CRC_RST),
             .CRCCLK(user_clk),
             .CRCDATAWIDTH(CRC_DATAWIDTH1),
             .CRCDATAVALID(CRC_DATAVALID1),
             .CRCIN(CRC_DATA1),
             .CRCOUT(CRC1)
     );
 
   assign CRC_DATAWIDTH1 = (axi4s_last_rdy_valid) ? s_axi_tx_tkeep_us_i[0:7] : 8'h0;
   assign CRC_DATAVALID1 = axi4s_rdy_valid;
   assign CRC_DATA1      = s_axi_tx_tdata_us[0:63];
 
     //--CRC reset assertion, this initializes the internal crc-reg with CRC_INIT value--//
   assign CRC_RST  = s_axi_tx_tsof_us && axi4s_rdy_valid;
     //--crc datawidth is equal to TKEEP during TLAST--//
   //--data can be input to block during CRC reset--//
 
 assign final_CRC = {
 		CRC1 }; 
 	  
     //__Register CRC calculated__//
   always @(posedge user_clk)
     CRC_reg <= `DLY final_CRC;
 
     //__Build DS output controls__/
   always @(posedge user_clk)
     if (reset_crc_block)
     begin
       s_axi_tx_tlast_ds    <= `DLY 1'b0;
       s_axi_tx_tkeep_ds    <= `DLY {8{1'b1}};
       s_axi_tx_tvalid_ds   <= `DLY 1'b0;
     end
     else if (s_axi_tx_tready_ds) 
     begin
       s_axi_tx_tlast_ds    <= `DLY (eof_ds_r | sof_eof_r | eof_sc_r);
       s_axi_tx_tkeep_ds    <= `DLY (eof_ds_r | sof_eof_r | eof_sc_r) ? tkeep_out : {8{1'b1}};
       s_axi_tx_tvalid_ds   <= `DLY !(idle_r | src_not_rdy_r | wait_r | sc_frame_r);
     end
               
     //__Build DS output data__//
   always @(posedge user_clk)
     if (reset_crc_block)
       s_axi_tx_tdata_ds <= `DLY 64'd0;
     else if (s_axi_tx_tready_ds) 
     begin     //--depending on input TKEEP, extract corresponding bytes from input data &
             // then append CRC in the next bytes--//
       if (sof_eof_r || eof_ds_r || eof_sc_r)
        s_axi_tx_tdata_ds <= `DLY 
    (rem_in == 7'd1 )? {s_axi_tx_tdata_us_r2[0:7],final_CRC,24'd0} :
    (rem_in == 7'd2 )? {s_axi_tx_tdata_us_r2[0:15],final_CRC,16'd0} :
    (rem_in == 7'd3 )? {s_axi_tx_tdata_us_r2[0:23],final_CRC,8'd0} :
    (rem_in == 7'd4 )? {s_axi_tx_tdata_us_r2[0:(DATA_WIDTH/2)-1],final_CRC} :
    (rem_in == 7'd5 )? {CRC_reg[24:(DATA_WIDTH/2 - 1)],56'd0}:
    (rem_in == 7'd6 )? {CRC_reg[16:(DATA_WIDTH/2 - 1)],48'd0}:
    (rem_in == 7'd7 )? {CRC_reg[8:(DATA_WIDTH/2 - 1)],40'd0}:
                 {CRC_reg,32'd0};
       else if (sof_sc_r || crc_r)
         s_axi_tx_tdata_ds <= `DLY
               (rem_in == 7'd7)? {s_axi_tx_tdata_us_r2[0:(DATA_WIDTH-1)-8],final_CRC[0:7]}:
               (rem_in == 7'd6)? {s_axi_tx_tdata_us_r2[0:(DATA_WIDTH-1)-16],final_CRC[0:15]}:
               (rem_in == 7'd5)? {s_axi_tx_tdata_us_r2[0:(DATA_WIDTH-1)-24],final_CRC[0:23]}:
               s_axi_tx_tdata_us_r2;
       else  //--otherwise just send the two stage pipeined data to output--//
         s_axi_tx_tdata_ds <= `DLY s_axi_tx_tdata_us_r2;
     end
     
 endmodule
