 ///////////////////////////////////////////////////////////////////////////////
 // Project:  Aurora 64B/66B
 // Company:  Xilinx
 //
 //
 // (c) Copyright 2014 - 2015 Xilinx, Inc. All rights reserved.
 //
 // This file contains confidential and proprietary information
 // of Xilinx, Inc. and is protected under U.S. and
 // international copyright and other intellectual property
 // laws.
 //
 // DISCLAIMER
 // This disclaimer is not a license and does not grant any
 // rights to the materials distributed herewith. Except as
 // otherwise provided in a valid license issued to you by
 // Xilinx, and to the maximum extent permitted by applicable
 // law: (1) THESE MATERIALS ARE MADE AVAILABLE "AS IS" AND
 // WITH ALL FAULTS, AND XILINX HEREBY DISCLAIMS ALL WARRANTIES
 // AND CONDITIONS, EXPRESS, IMPLIED, OR STATUTORY, INCLUDING
 // BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, NON-
 // INFRINGEMENT, OR FITNESS FOR ANY PARTICULAR PURPOSE; and
 // (2) Xilinx shall not be liable (whether in contract or tort,
 // including negligence, or under any other theory of
 // liability) for any loss or damage of any kind or nature
 // related to, arising under or in connection with these
 // materials, including for any direct, or any indirect,
 // special, incidental, or consequential loss or damage
 // (including loss of data, profits, goodwill, or any type of
 // loss or damage suffered as a result of any action brought
 // by a third party) even if such damage or loss was
 // reasonably foreseeable or Xilinx had been advised of the
 // possibility of the same.
 //
 // CRITICAL APPLICATIONS
 // Xilinx products are not designed or intended to be fail-
 // safe, or for use in any application requiring fail-safe
 // performance, such as life-support or safety devices or
 // systems, Class III medical devices, nuclear facilities,
 // applications related to the deployment of airbags, or any
 // other applications that could lead to death, personal
 // injury, or severe property or environmental damage
 // (individually and collectively, "Critical
 // Applications"). Customer assumes the sole risk and
 // liability of any use of Xilinx products in Critical
 // Applications, subject only to applicable laws and
 // regulations governing limitations on product liability.
 //
 // THIS COPYRIGHT NOTICE AND DISCLAIMER MUST BE RETAINED AS
 // PART OF THIS FILE AT ALL TIMES.
 
 /////////////////////////////////////////////////////////////////////////////////////
 //
 // Module RX_CRC
 // Generated by Xilinx Aurora 64B66B
 
 `timescale 1 ns/1 ps

 `define DLY #1
(* DowngradeIPIdentifiedWarnings="yes" *)
  
 //***********************************Entity Declaration*******************************
 module aurora_64b66b_0_rx_crc_axi (
   m_axi_rx_tdata_ds,
   m_axi_rx_tvalid_ds,
   m_axi_rx_tready_ds,
   m_axi_rx_tkeep_ds,
   m_axi_rx_tlast_ds,
   m_axi_rx_tdata_us,
   m_axi_rx_tvalid_us,
   m_axi_rx_tready_us,
   m_axi_rx_tkeep_us,
   m_axi_rx_tlast_us,
   crc_pass_fail_n,
   crc_valid,
   reset,
   channel_up,
   user_clk
 );
 
 parameter CRC_INIT = 32'hFFFFFFFF;
 parameter DATA_WIDTH = 64;
 parameter REM_WIDTH = 3;
 parameter STRB_WIDTH = 8;
 
 
   output [0:(DATA_WIDTH-1)] m_axi_rx_tdata_ds;
   output [0:7]  m_axi_rx_tkeep_ds;                   
   output      	m_axi_rx_tlast_ds;
   output      	m_axi_rx_tvalid_ds;
   input       	m_axi_rx_tready_ds;
   output      	m_axi_rx_tready_us;
   output      	crc_pass_fail_n;
   output      	crc_valid;
   input [0:(DATA_WIDTH-1)]  m_axi_rx_tdata_us;
   input [0:7]   m_axi_rx_tkeep_us;                   
   input       	m_axi_rx_tlast_us;
   input       	m_axi_rx_tvalid_us;
   input       	reset;
   input       	channel_up;
   input       	user_clk;
     
   reg [0:(DATA_WIDTH-1)]    m_axi_rx_tdata_ds;
   reg [0:7]     m_axi_rx_tkeep_ds;                   
   reg       	m_axi_rx_tlast_ds;
   reg       	m_axi_rx_tvalid_ds;
     
   reg       	crc_valid;
//--tkeep to rem conversion logic--{
reg [(REM_WIDTH-1):0] rem_us;
reg [(STRB_WIDTH-1):0] i;
reg found_rem = 1'b0;

always @(found_rem or m_axi_rx_tkeep_us)
begin
    found_rem = 1'b0;
    rem_us = {(STRB_WIDTH-1){1'b0}};
    for(i = 0;i < STRB_WIDTH; i = i + 1)
    begin
        if ((m_axi_rx_tkeep_us[i] == 1'b0) && (found_rem == 1'b0))
        begin
            rem_us = i;
            found_rem = 1'b1;
        end
    end
end
//--tkeep to rem conversion logic--}
     
     //__Signal declaration for one-hot encoded FSM__//
     reg   idle_r;   //--Idle or power on state
     reg   sc_frame_r; //--single cycle frame received state
     reg   sof_r;    //--sof received state (not single cycle frame)
     reg   sof_eof_r;  //--build single cycle frame output--//
     reg   sof_ds_r; //--build sof state
     reg   data_r;   //--data state
     reg   eof_ds_r; //--build eof state
     reg   crc_r;    //--final CRC state
     
     wire  idle_c;
     wire  sc_frame_c;
     wire  sof_c;
     wire  sof_eof_c;
     wire  sof_ds_c;
     wire  data_c;
     wire  eof_ds_c;
     wire  crc_c;
     
     //__internal register declaration__//
     reg    m_axi_rx_tlast_us_r;   //--registered TLAST input
     reg    m_axi_rx_tsof_us_r;   //--registered SOF input
     reg [0:7] tkeep_in;     //--TKEEP input
     reg [0:7] tkeep_out;    //--TKEEP output
     reg [0:(DATA_WIDTH-1)]  m_axi_rx_tdata_us_r;    //--data pipe-I
     reg [0:(DATA_WIDTH-1)]  m_axi_rx_tdata_us_2r;   //--data pipe-II
     reg    m_axi_rx_tready_us_2r;
     reg    axi4s_rdy_valid_r;   //-- axi4s_rdy_valid registered
     reg [1:0] 	count;      //--count to deassert dst-rdy-us after eof reception
     reg [0:(DATA_WIDTH/2-1)]  received_CRC; //--received CRC extracted and stored in this register
     reg 	CRC_RESET_r=1'b0;  //TODO
     reg    m_axi_rx_tlast_us_r1;   //-- continously registered TLAST input
     reg    m_axi_rx_tlast_us_r2;   //-- continously registered TLAST input
     reg    load_waiting_crc;   //-- if consecutive or close by (1 cycle apart) TLAST appeared, received_crc had to be hold for one cycle, this signal loads the current value afterwards

     
     //__internal wire declaration__//
     wire [0:7] 	tkeep_int_i;     //--TKEEP input
     wire    CRC_RESET;
     wire    CRC_DATAVALID;   
     wire    CRC_DATAVALID1;   
     wire [0:31] CRC1;      //__CRC calculated
     wire [0:7]  CRC_DATAWIDTH1;  //__CRC datawidth
     wire [0:63] CRC_DATA1;   //__data input to CRC block
     wire   axi4s_rdy_valid;   // AXI-4 Stream handshake valid
     wire   m_axi_rx_tready_us_i;
     wire [0:(DATA_WIDTH/2-1)] tx_crc_sc;
     wire [0:(DATA_WIDTH/2-1)] tx_crc;
     wire [0:(DATA_WIDTH/2-1)] final_CRC;
      
     wire    		reset_crc_block;  
     //SOF generation signals  
     wire   m_axi_rx_tsof_us;
     wire   new_pkt; 
     reg    new_pkt_r;
  
     //____________Main code begins here________________//
  assign reset_crc_block = reset || !channel_up;
  //SOF generation
  assign new_pkt           = ( m_axi_rx_tvalid_us & m_axi_rx_tready_us & m_axi_rx_tlast_us ) ? 1'b0 : ((m_axi_rx_tvalid_us && m_axi_rx_tready_us && !m_axi_rx_tlast_us ) ? 1'b1 : new_pkt_r);
  assign m_axi_rx_tsof_us  = ( ( m_axi_rx_tvalid_us & m_axi_rx_tready_us & m_axi_rx_tlast_us ) ? ((new_pkt_r) ? 1'b0 : 1'b1) : (new_pkt && (!new_pkt_r)));
 
 always @ (posedge user_clk)
 begin
   if(reset_crc_block)
     new_pkt_r <= `DLY 1'b0;
   else
     new_pkt_r <= `DLY new_pkt;
 end
     
     //__Initialization & state assignment for FSM__//
   always @(posedge user_clk)
     if (reset_crc_block)
     begin
       idle_r      <= `DLY 1'b1;
       sc_frame_r  <= `DLY 1'b0;
       sof_r       <= `DLY 1'b0;
       sof_eof_r   <= `DLY 1'b0;
       sof_ds_r    <= `DLY 1'b0;
       data_r      <= `DLY 1'b0;
       eof_ds_r    <= `DLY 1'b0;
       crc_r       <= `DLY 1'b0;
     end
     else if (m_axi_rx_tready_ds)
     begin
       idle_r      <= `DLY idle_c;
       sc_frame_r  <= `DLY sc_frame_c;
       sof_r       <= `DLY sof_c;
       sof_eof_r   <= `DLY sof_eof_c;
       sof_ds_r    <= `DLY sof_ds_c;
       data_r      <= `DLY data_c;
       eof_ds_r    <= `DLY eof_ds_c;
       crc_r       <= `DLY crc_c;
     end
     
     //__Combinatorial logic for FSM__//
     
     //--stay in idle when there is no input SOF or 
     //when current frame calculations complete--//
   assign idle_c = ((idle_r || eof_ds_r || sof_eof_r) & 
                 (!m_axi_rx_tsof_us || !axi4s_rdy_valid));
     //--reach this when single cycle frame is received--//  
   assign sc_frame_c = (idle_r || eof_ds_r || sof_eof_r) & 
                   m_axi_rx_tsof_us & m_axi_rx_tlast_us & axi4s_rdy_valid;
     //--reach this when non-single cycle frame is received--//
   assign sof_c  = ((idle_r || eof_ds_r || sof_eof_r) & 
                 m_axi_rx_tsof_us & !m_axi_rx_tlast_us & axi4s_rdy_valid) ||
 						(sof_r && !axi4s_rdy_valid);
     //--build single cycle frame output--//
   assign sof_eof_c  = (sof_r & axi4s_rdy_valid & m_axi_rx_tlast_us & (m_axi_rx_tkeep_us[4] == 1'b0)) || sc_frame_r;
     //--build SOF output--//
   assign sof_ds_c   = sof_r & axi4s_rdy_valid & ((m_axi_rx_tlast_us & (m_axi_rx_tkeep_us[4] == 1'b1)) | !m_axi_rx_tlast_us);
     //--data input state--//
   assign data_c = (sof_ds_r & ((!m_axi_rx_tlast_us & !m_axi_rx_tlast_us_r) || !axi4s_rdy_valid)) ||
               (data_r & (!m_axi_rx_tlast_us || !axi4s_rdy_valid));
     //--final CRC state--//
   assign crc_c  = (sof_ds_r & m_axi_rx_tlast_us & (m_axi_rx_tkeep_us[4] == 1'b1) & axi4s_rdy_valid) ||
             (data_r & m_axi_rx_tlast_us & (m_axi_rx_tkeep_us[4] == 1'b1) & axi4s_rdy_valid);
     //--build TLAST output--//        
   assign eof_ds_c =(sof_ds_r & ((m_axi_rx_tlast_us_r & axi4s_rdy_valid_r) || (m_axi_rx_tlast_us & (m_axi_rx_tkeep_us[4] == 1'b0) & axi4s_rdy_valid))) ||
             (data_r & m_axi_rx_tlast_us & (m_axi_rx_tkeep_us[4] == 1'b0) & axi4s_rdy_valid) || crc_r; 
   
     //__Store TKEEP value and build output TKEEP__//
   always @(posedge user_clk)
     if (m_axi_rx_tlast_us & axi4s_rdy_valid)
     begin
       tkeep_out <= `DLY (m_axi_rx_tkeep_us[4] ? {m_axi_rx_tkeep_us[4:7],4'h0} : {{4{1'b1}},m_axi_rx_tkeep_us[0:3]});  //--output TKEEP is input TKEEP + 8'hFF per lane
       tkeep_in  <= `DLY m_axi_rx_tkeep_us;
     end
       
     //__input signals registered__//
   always @(posedge user_clk)
     if (axi4s_rdy_valid)
     begin
       m_axi_rx_tlast_us_r   <= `DLY m_axi_rx_tlast_us;
       m_axi_rx_tsof_us_r    <= `DLY m_axi_rx_tsof_us;
       m_axi_rx_tdata_us_r   <= `DLY m_axi_rx_tdata_us;
     end
       
     //--register data and src rdy inputs--//
   always @(posedge user_clk)
   if (m_axi_rx_tready_ds || m_axi_rx_tlast_us_r)
   begin
     m_axi_rx_tdata_us_2r    <= `DLY m_axi_rx_tdata_us_r;
     m_axi_rx_tready_us_2r   <= `DLY CRC_DATAVALID;
   end
 
   //__store the received CRC__
   always @(posedge user_clk) begin
      if(m_axi_rx_tkeep_us[3]) 
        received_CRC  <= `DLY tx_crc_sc;
      else if (m_axi_rx_tlast_us && !m_axi_rx_tsof_us & axi4s_rdy_valid)
        received_CRC  <= `DLY tx_crc;
      end // always @ (posedge user_clk)
 
aurora_64b66b_0_CRC_TOP #(
         .CRC_INIT(CRC_INIT)
         ) rx_crc_gen_i1 (
             .CRCRESET(CRC_RESET),
             .CRCCLK(user_clk),
             .CRCDATAWIDTH(CRC_DATAWIDTH1),
             .CRCDATAVALID(CRC_DATAVALID1),
             .CRCIN(CRC_DATA1),
             .CRCOUT(CRC1)
     );
 
   assign CRC_DATAWIDTH1 = tkeep_int_i[0:7];
   assign CRC_DATAVALID1 = CRC_DATAVALID;
   assign CRC_DATA1 = m_axi_rx_tdata_us_r[0:63];
  
     
     //--CRC reset is give one cycle later so that TKEEP information
     //which translates into crc-data-width can be calculated early--//
 	assign CRC_RESET  = (m_axi_rx_tsof_us_r & axi4s_rdy_valid_r) ? (axi4s_rdy_valid || m_axi_rx_tlast_us_r) : (axi4s_rdy_valid & CRC_RESET_r);
 
 	always @(posedge user_clk)
       if (m_axi_rx_tsof_us_r & !m_axi_rx_tlast_us_r & axi4s_rdy_valid_r)
          CRC_RESET_r <= `DLY !axi4s_rdy_valid;
       else if (axi4s_rdy_valid & CRC_RESET_r)
          CRC_RESET_r <= `DLY 1'b0;
 
 	//--crc datawidth depending on input TKEEP--//
   assign tkeep_int_i = (m_axi_rx_tlast_us & !m_axi_rx_tkeep_us[4]) ? {{4{1'b1}},m_axi_rx_tkeep_us[0:3]} :
                (m_axi_rx_tlast_us_r & tkeep_in[4]) ? {tkeep_in[4:7],4'h0} : {8{1'b1}};

       //when input TKEEP > 8'hFF during input TLAST--//
 	assign CRC_DATAVALID = (m_axi_rx_tsof_us & axi4s_rdy_valid) ? 1'b0 :
             ((m_axi_rx_tlast_us_r & (tkeep_in[4] == 1'b1) & axi4s_rdy_valid_r) || axi4s_rdy_valid || CRC_RESET);
 
  
       //--Build dst-rdy-us output--//
   assign m_axi_rx_tready_us = m_axi_rx_tready_us_i;
   //assign m_axi_rx_tready_us_i = m_axi_rx_tready_ds || ~(|count);  //DEBUG
   assign m_axi_rx_tready_us_i = (m_axi_rx_tready_ds && (count == 2'b00));
   
   //__deassert m_axi_rx_tready_us for 2 cycles after m_axi_rx_tlast_us reception__//
       
   always @(posedge user_clk)
     if (reset_crc_block)
       count <= `DLY 2'b00;
     else if (m_axi_rx_tlast_us & axi4s_rdy_valid)
       //count <=  2'b10;
       count <= `DLY 2'b01;
     else if (|count && m_axi_rx_tready_ds)
       count <= `DLY count >> 1;
     //--Axi-4s handshake valid--//  
   assign axi4s_rdy_valid = m_axi_rx_tvalid_us ;
     //--register axi4s_rdy_valid for use--//
   always @(posedge user_clk)
     axi4s_rdy_valid_r  <= `DLY axi4s_rdy_valid;
     
     //__Build DS output__//
   always @(posedge user_clk)
     if (reset_crc_block)
     begin
       m_axi_rx_tlast_ds   <= `DLY 1'b0;
       m_axi_rx_tvalid_ds  <= `DLY 1'b0;
       m_axi_rx_tkeep_ds   <= `DLY {8{1'b1}};
     end
     else if (m_axi_rx_tready_ds)
     begin
       m_axi_rx_tlast_ds   <= `DLY (sof_eof_r || eof_ds_r);
       m_axi_rx_tvalid_ds  <= `DLY m_axi_rx_tready_us_2r;
       m_axi_rx_tkeep_ds   <= `DLY (sof_eof_r || eof_ds_r) ? tkeep_out : {8{1'b1}};
     end
     
   always @(posedge user_clk)
       m_axi_rx_tdata_ds   <= `DLY m_axi_rx_tdata_us_2r;

     //__Extract CRC from input data__//
     
     //__CRC extraction for single cycle frame inputs__//
   assign tx_crc_sc  = 
             (rem_us == 7'd7) ? m_axi_rx_tdata_us[24:55]: 
             (rem_us == 7'd6) ? m_axi_rx_tdata_us[16:47]: 
             (rem_us == 7'd5) ? m_axi_rx_tdata_us[8:39]: 
             (rem_us == 7'd4) ? m_axi_rx_tdata_us[0:31]: 
              m_axi_rx_tdata_us[DATA_WIDTH/2:DATA_WIDTH-1]; 
     //__CRC extraction for all other cases__//      
   assign tx_crc =
             (rem_us == 7'd3) ? {m_axi_rx_tdata_us_r[56:63],m_axi_rx_tdata_us[0:23]} :
             (rem_us == 7'd2) ? {m_axi_rx_tdata_us_r[48:63],m_axi_rx_tdata_us[0:15]} :
             (rem_us == 7'd1) ? {m_axi_rx_tdata_us_r[40:63],m_axi_rx_tdata_us[0:7]} :
             m_axi_rx_tdata_us[0:(DATA_WIDTH/2)-1];
       
   assign final_CRC = {
 		CRC1 }; 
      
          //__compare the received CRC with the CRC calculated__//
   assign crc_pass_fail_n  = (received_CRC == final_CRC);
       
       //__crc_pass_fail_n to be considered only when crc_valid is asserted__//
   always @(posedge user_clk)
     if (reset_crc_block)
       crc_valid <= `DLY 1'b0;
     else
       crc_valid <= `DLY (sof_eof_r || eof_ds_r) & (!axi4s_rdy_valid);
       
 endmodule
 
