// file: sys_mon.v
// (c) Copyright 2013 - 2013 Xilinx, Inc. All rights reserved.
// 
// This file contains confidential and proprietary information
// of Xilinx, Inc. and is protected under U.S. and
// international copyright and other intellectual property
// laws.
// 
// DISCLAIMER
// This disclaimer is not a license and does not grant any
// rights to the materials distributed herewith. Except as
// otherwise provided in a valid license issued to you by
// Xilinx, and to the maximum extent permitted by applicable
// law: (1) THESE MATERIALS ARE MADE AVAILABLE "AS IS" AND
// WITH ALL FAULTS, AND XILINX HEREBY DISCLAIMS ALL WARRANTIES
// AND CONDITIONS, EXPRESS, IMPLIED, OR STATUTORY, INCLUDING
// BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, NON-
// INFRINGEMENT, OR FITNESS FOR ANY PARTICULAR PURPOSE; and
// (2) Xilinx shall not be liable (whether in contract or tort,
// including negligence, or under any other theory of
// liability) for any loss or damage of any kind or nature
// related to, arising under or in connection with these
// materials, including for any direct, or any indirect,
// special, incidental, or consequential loss or damage
// (including loss of data, profits, goodwill, or any type of
// loss or damage suffered as a result of any action brought
// by a third party) even if such damage or loss was
// reasonably foreseeable or Xilinx had been advised of the
// possibility of the same.
// 
// CRITICAL APPLICATIONS
// Xilinx products are not designed or intended to be fail-
// safe, or for use in any application requiring fail-safe
// performance, such as life-support or safety devices or
// systems, Class III medical devices, nuclear facilities,
// applications related to the deployment of airbags, or any
// other applications that could lead to death, personal
// injury, or severe property or environmental damage
// (individually and collectively, "Critical
// Applications"). Customer assumes the sole risk and
// liability of any use of Xilinx products in Critical
// Applications, subject only to applicable laws and
// regulations governing limitations on product liability.
// 
// THIS COPYRIGHT NOTICE AND DISCLAIMER MUST BE RETAINED AS
// PART OF THIS FILE AT ALL TIMES.
`timescale 1ns / 1 ps

(* CORE_GENERATION_INFO = "sys_mon,system_management_wiz_v1_3_13,{x_ipProduct=Vivado 2020.2,x_ipVendor=xilinx.com,x_ipLibrary=ip,x_ipName=system_management_wiz,x_ipVersion=1.3,x_ipCoreRevision=13,x_ipLanguage=VERILOG,x_ipSimLanguage=MIXED,C_FAMILY=kintexu,C_IS_DIABLO=0,C_DUAL0_REGISTER=0,C_DUAL1_REGISTER=0,C_DUAL2_REGISTER=0,C_DUAL3_REGISTER=0,C_COMMON_N_SOURCE=Null,C_ENABLE_ADC_DATA_OUT_MASTER=0,C_ENABLE_ADC_DATA_OUT_SLAVE0=0,C_ENABLE_ADC_DATA_OUT_SLAVE1=0,C_ENABLE_ADC_DATA_OUT_SLAVE2=0,C_ENABLE_DUAL_SEQUENCE_MODE=0,c_component_name=sys_mon,C_SIM_FILE_SEL=Default,C_SIM_DEVICE=NULL,C_SIM_FILE_REL_PATH=./,C_SIM_FILE_NAME=design,C_HAS_DCLK=1,C_HAS_DRP=1,C_HAS_RESET=1,C_HAS_CONVST=0,C_HAS_CONVSTCLK=0,C_HAS_VP=1,C_HAS_VN=1,C_HAS_CHANNEL=1,C_HAS_EOC=1,C_HAS_EOS=1,C_HAS_BUSY=1,C_HAS_JTAGLOCKED=0,C_HAS_JTAGMODIFIED=0,C_HAS_JTAGBUSY=0,C_HAS_EXTERNAL_MUX=0,C_EXTERNAL_MUXADDR_ENABLE=0,C_EXTERNAL_MUX_CHANNEL=VP_VN,C_DCLK_FREQUENCY=250,C_SAMPLING_RATE=196232.33908948195,C_HAS_OT_ALARM=0,C_HAS_USER_TEMP_ALARM=0,C_HAS_UNDER_OT_ALARM=0,C_HAS_UNDER_TEMP_ALARM=0,C_HAS_VCCINT_ALARM=0,C_HAS_VCCPSINTFP_ALARM=0,C_HAS_VCCPSAUX_ALARM=0,C_HAS_VCCPSINTLP_ALARM=0,C_HAS_VCCAUX_ALARM=0,C_HAS_VBRAM_ALARM=0,C_HAS_VCCPINT_ALARM=0,C_HAS_VCCPAUX_ALARM=0,C_HAS_VCCDDRO_ALARM=0,C_CONFIGURATION_R0=0,C_CONFIGURATION_R1=16287,C_CONFIGURATION_R2=12544,C_CONFIGURATION_R4=0,C_ALARM_LIMIT_R0=46883,C_ALARM_LIMIT_R1=20097,C_ALARM_LIMIT_R2=41287,C_ALARM_LIMIT_R3=52115,C_ALARM_LIMIT_R4=43615,C_ALARM_LIMIT_R5=18787,C_ALARM_LIMIT_R6=38229,C_ALARM_LIMIT_R7=44923,C_ALARM_LIMIT_R8=20097,C_ALARM_LIMIT_R9=18787,C_ALARM_LIMIT_R10=18787,C_ALARM_LIMIT_R11=17694,C_ALARM_LIMIT_R12=18787,C_ALARM_LIMIT_R13=17694,C_ALARM_LIMIT_R14=39540,C_ALARM_LIMIT_R15=37355,C_SEQUENCE_R0=256,C_SEQUENCE_SLAVE0_SSIT_R0=256,C_SEQUENCE_SLAVE1_SSIT_R0=256,C_SEQUENCE_SLAVE2_SSIT_R0=256,C_SEQUENCE_R1=0,C_SEQUENCE_R2=0,C_SEQUENCE_R3=0,C_SEQUENCE_R4=0,C_SEQUENCE_R5=0,C_SEQUENCE_R6=0,C_SEQUENCE_R7=0,C_VPVN=0,C_VAUX0=0,C_VAUX1=0,C_VAUX2=0,C_VAUX3=0,C_VAUX4=0,C_VAUX5=0,C_VAUX6=0,C_VAUX7=0,C_VAUX8=0,C_VAUX9=0,C_VAUX10=0,C_VAUX11=0,C_VAUX12=0,C_VAUX13=0,C_VAUX14=0,C_VAUX15=0,C_HAS_AXI=0,C_HAS_PMC=0,C_HAS_PMC_MASTER=0,C_HAS_AXI4STREAM=0,C_HAS_TEMP_BUS=0,C_HAS_SLAVE0_SSIT_TEMP_CH=1,C_HAS_SLAVE1_SSIT_TEMP_CH=1,C_HAS_SLAVE2_SSIT_TEMP_CH=1,C_FIFO_DEPTH=7,C_INCLUDE_INTR=1,C_IS_SSIT_SLAVE0=0,C_IS_SSIT_SLAVE1=0,C_IS_SSIT_SLAVE2=0,C_ENABLE_SLAVE0=0,C_ENABLE_SLAVE1=0,C_ENABLE_SLAVE2=0,C_IS_SSIT_SLAVE0_ANALOG_BANK=0,C_IS_SSIT_SLAVE1_ANALOG_BANK=0,C_IS_SSIT_SLAVE2_ANALOG_BANK=0,C_HAS_I2C=0,C_HAS_PMBUS=0,C_HAS_I2C_SLAVE=0,C_I2C_SLAVE_ADDRESS=32,C_I2C_SLAVE0_ADDRESS=32,C_I2C_SLAVE1_ADDRESS=32,C_I2C_SLAVE2_ADDRESS=32,C_CONFIGURATION_R3=15,C_CONFIGURATION_SLAVE0_SSIT_R3=15,C_CONFIGURATION_SLAVE1_SSIT_R3=15,C_CONFIGURATION_SLAVE2_SSIT_R3=15,C_CONFIGURATION_R4_1=12,C_CONFIGURATION_R4_2=13,C_CONFIGURATION_R4_3=14,C_CONFIGURATION_R4_4=13,C_CONFIGURATION_SLAVE0_SSIT_R4_1=12,C_CONFIGURATION_SLAVE0_SSIT_R4_2=13,C_CONFIGURATION_SLAVE0_SSIT_R4_3=14,C_CONFIGURATION_SLAVE0_SSIT_R4_4=12,C_CONFIGURATION_SLAVE1_SSIT_R4_1=12,C_CONFIGURATION_SLAVE1_SSIT_R4_2=13,C_CONFIGURATION_SLAVE1_SSIT_R4_3=14,C_CONFIGURATION_SLAVE1_SSIT_R4_4=12,C_CONFIGURATION_SLAVE2_SSIT_R4_1=12,C_CONFIGURATION_SLAVE2_SSIT_R4_2=13,C_CONFIGURATION_SLAVE2_SSIT_R4_3=14,C_CONFIGURATION_SLAVE2_SSIT_R4_4=12,C_ALARM_LIMIT_USL1=39103,C_ALARM_LIMIT_USU1=39540,C_ALARM_LIMIT_USL2=19442,C_ALARM_LIMIT_USU2=19879,C_ALARM_LIMIT_USL3=39103,C_ALARM_LIMIT_USU3=39540,C_ALARM_LIMIT_USL4=19550,C_ALARM_LIMIT_USU4=19769,C_ALARM_LIMIT_SLAVE0_SSIT_USL1=39103,C_ALARM_LIMIT_SLAVE0_SSIT_USU1=39540,C_ALARM_LIMIT_SLAVE0_SSIT_USL2=19442,C_ALARM_LIMIT_SLAVE0_SSIT_USU2=19879,C_ALARM_LIMIT_SLAVE0_SSIT_USL3=39103,C_ALARM_LIMIT_SLAVE0_SSIT_USU3=39540,C_ALARM_LIMIT_SLAVE0_SSIT_USL4=19550,C_ALARM_LIMIT_SLAVE0_SSIT_USU4=19769,C_ALARM_LIMIT_SLAVE1_SSIT_USL1=39103,C_ALARM_LIMIT_SLAVE1_SSIT_USU1=39540,C_ALARM_LIMIT_SLAVE1_SSIT_USL2=19442,C_ALARM_LIMIT_SLAVE1_SSIT_USU2=19879,C_ALARM_LIMIT_SLAVE1_SSIT_USL3=39103,C_ALARM_LIMIT_SLAVE1_SSIT_USU3=39540,C_ALARM_LIMIT_SLAVE1_SSIT_USL4=19550,C_ALARM_LIMIT_SLAVE1_SSIT_USU4=19769,C_ALARM_LIMIT_SLAVE2_SSIT_USL1=39103,C_ALARM_LIMIT_SLAVE2_SSIT_USU1=39540,C_ALARM_LIMIT_SLAVE2_SSIT_USL2=19442,C_ALARM_LIMIT_SLAVE2_SSIT_USU2=19879,C_ALARM_LIMIT_SLAVE2_SSIT_USL3=39103,C_ALARM_LIMIT_SLAVE2_SSIT_USU3=39540,C_ALARM_LIMIT_SLAVE2_SSIT_USL4=19550,C_ALARM_LIMIT_SLAVE2_SSIT_USU4=19769,C_SEQUENCE_R8=0,C_DUAL_SEQUENCE_R2=0,C_DUAL_SEQUENCE_R1=0,C_DUAL_SEQUENCE_R0=256,C_AVG_VUSER=0,C_SEQUENCE_SLAVE0_SSIT_R8=0,C_AVG_SLAVE0_SSIT_VUSER=0,C_SEQUENCE_SLAVE1_SSIT_R8=0,C_AVG_SLAVE1_SSIT_VUSER=0,C_SEQUENCE_SLAVE2_SSIT_R8=0,C_AVG_SLAVE2_SSIT_VUSER=0,C_HAS_USER_SUPPLY0_ALARM=0,C_HAS_USER_SUPPLY1_ALARM=0,C_HAS_USER_SUPPLY2_ALARM=0,C_HAS_USER_SUPPLY3_ALARM=0,C_AVERAGE_EN_VUSER0=0,C_AVERAGE_EN_VUSER1=0,C_AVERAGE_EN_VUSER2=0,C_AVERAGE_EN_VUSER3=0,C_HAS_USER_SUPPLY0_SLAVE0_SSIT_ALARM=0,C_HAS_USER_SUPPLY1_SLAVE0_SSIT_ALARM=0,C_HAS_USER_SUPPLY2_SLAVE0_SSIT_ALARM=0,C_HAS_USER_SUPPLY3_SLAVE0_SSIT_ALARM=0,C_AVERAGE_EN_SLAVE0_SSIT_VUSER0=0,C_AVERAGE_EN_SLAVE0_SSIT_VUSER1=0,C_AVERAGE_EN_SLAVE0_SSIT_VUSER2=0,C_AVERAGE_EN_SLAVE0_SSIT_VUSER3=0,C_HAS_USER_SUPPLY0_SLAVE1_SSIT_ALARM=0,C_HAS_USER_SUPPLY1_SLAVE1_SSIT_ALARM=0,C_HAS_USER_SUPPLY2_SLAVE1_SSIT_ALARM=0,C_HAS_USER_SUPPLY3_SLAVE1_SSIT_ALARM=0,C_AVERAGE_EN_SLAVE1_SSIT_VUSER0=0,C_AVERAGE_EN_SLAVE1_SSIT_VUSER1=0,C_AVERAGE_EN_SLAVE1_SSIT_VUSER2=0,C_AVERAGE_EN_SLAVE1_SSIT_VUSER3=0,C_HAS_USER_SUPPLY0_SLAVE2_SSIT_ALARM=0,C_HAS_USER_SUPPLY1_SLAVE2_SSIT_ALARM=0,C_HAS_USER_SUPPLY2_SLAVE2_SSIT_ALARM=0,C_HAS_USER_SUPPLY3_SLAVE2_SSIT_ALARM=0,C_AVERAGE_EN_SLAVE2_SSIT_VUSER0=0,C_AVERAGE_EN_SLAVE2_SSIT_VUSER1=0,C_AVERAGE_EN_SLAVE2_SSIT_VUSER2=0,C_AVERAGE_EN_SLAVE2_SSIT_VUSER3=0,C_I2C_CLK_PERIOD=2500.000,C_USER_SUPPLY0_SOURCE=VCCO,C_USER_SUPPLY1_SOURCE=VCCINT,C_USER_SUPPLY2_SOURCE=VCCAUX,C_USER_SUPPLY3_SOURCE=VCCO_BOT,C_USER_SUPPLY0_BANK=44,C_USER_SUPPLY1_BANK=44,C_USER_SUPPLY2_BANK=44,C_USER_SUPPLY3_BANK=65,C_USER_SUPPLY0_SLAVE0_SSIT_SOURCE=VCCO,C_USER_SUPPLY1_SLAVE0_SSIT_SOURCE=VCCINT,C_USER_SUPPLY2_SLAVE0_SSIT_SOURCE=VCCAUX,C_USER_SUPPLY3_SLAVE0_SSIT_SOURCE=VCCO_TOP,C_USER_SUPPLY0_SLAVE0_SSIT_BANK=44,C_USER_SUPPLY1_SLAVE0_SSIT_BANK=44,C_USER_SUPPLY2_SLAVE0_SSIT_BANK=44,C_USER_SUPPLY3_SLAVE0_SSIT_BANK=65,C_USER_SUPPLY0_SLAVE1_SSIT_SOURCE=VCCO,C_USER_SUPPLY1_SLAVE1_SSIT_SOURCE=VCCINT,C_USER_SUPPLY2_SLAVE1_SSIT_SOURCE=VCCAUX,C_USER_SUPPLY3_SLAVE1_SSIT_SOURCE=VCCO_TOP,C_USER_SUPPLY0_SLAVE1_SSIT_BANK=44,C_USER_SUPPLY1_SLAVE1_SSIT_BANK=44,C_USER_SUPPLY2_SLAVE1_SSIT_BANK=44,C_USER_SUPPLY3_SLAVE1_SSIT_BANK=65,C_USER_SUPPLY0_SLAVE2_SSIT_SOURCE=VCCO,C_USER_SUPPLY1_SLAVE2_SSIT_SOURCE=VCCINT,C_USER_SUPPLY2_SLAVE2_SSIT_SOURCE=VCCAUX,C_USER_SUPPLY3_SLAVE2_SSIT_SOURCE=VCCO_TOP,C_USER_SUPPLY0_SLAVE2_SSIT_BANK=44,C_USER_SUPPLY1_SLAVE2_SSIT_BANK=44,C_USER_SUPPLY2_SLAVE2_SSIT_BANK=44,C_USER_SUPPLY3_SLAVE2_SSIT_BANK=65,C_HAS_VUSER0=0,C_HAS_VUSER1=0,C_HAS_VUSER2=0,C_HAS_VUSER3=0,C_HAS_SLAVE0_SSIT_VUSER0=0,C_HAS_SLAVE0_SSIT_VUSER1=0,C_HAS_SLAVE0_SSIT_VUSER2=0,C_HAS_SLAVE0_SSIT_VUSER3=0,C_HAS_SLAVE1_SSIT_VUSER0=0,C_HAS_SLAVE1_SSIT_VUSER1=0,C_HAS_SLAVE1_SSIT_VUSER2=0,C_HAS_SLAVE1_SSIT_VUSER3=0,C_HAS_SLAVE2_SSIT_VUSER0=0,C_HAS_SLAVE2_SSIT_VUSER1=0,C_HAS_SLAVE2_SSIT_VUSER2=0,C_HAS_SLAVE2_SSIT_VUSER3=0,C_DUAL_SEQ=0,C_DIV_VUSER0=3,C_DIV_VUSER1=3,C_DIV_VUSER2=3,C_DIV_VUSER3=6,C_DIV_VUSER0_SLAVE0=3,C_DIV_VUSER1_SLAVE0=3,C_DIV_VUSER2_SLAVE0=3,C_DIV_VUSER3_SLAVE0=6,C_DIV_VUSER0_SLAVE1=3,C_DIV_VUSER1_SLAVE1=3,C_DIV_VUSER2_SLAVE1=3,C_DIV_VUSER3_SLAVE1=6,C_DIV_VUSER0_SLAVE2=3,C_DIV_VUSER1_SLAVE2=3,C_DIV_VUSER2_SLAVE2=3,C_DIV_VUSER3_SLAVE2=6,C_CHANNEL_CNT=3,C_VAUXN0_LOC=AP21,C_VAUXP0_LOC=AP20,C_VAUXN1_LOC=AN22,C_VAUXP1_LOC=AM22,C_VAUXN2_LOC=AL25,C_VAUXP2_LOC=AL24,C_VAUXN3_LOC=AK20,C_VAUXP3_LOC=AJ20,C_VAUXN4_LOC=AJ25,C_VAUXP4_LOC=AH24,C_VAUXN5_LOC=AF24,C_VAUXP5_LOC=AF23,C_VAUXN6_LOC=AG22,C_VAUXP6_LOC=AF22,C_VAUXN7_LOC=AH21,C_VAUXP7_LOC=AG21,C_VAUXN8_LOC=AN24,C_VAUXP8_LOC=AM24,C_VAUXN9_LOC=AN21,C_VAUXP9_LOC=AM21,C_VAUXN10_LOC=AL23,C_VAUXP10_LOC=AL22,C_VAUXN11_LOC=AM20,C_VAUXP11_LOC=AL20,C_VAUXN12_LOC=AG25,C_VAUXP12_LOC=AG24,C_VAUXN13_LOC=AE26,C_VAUXP13_LOC=AE25,C_VAUXN14_LOC=AE23,C_VAUXP14_LOC=AE22,C_VAUXN15_LOC=AE20,C_VAUXP15_LOC=AD20,C_I2C_SCLK_LOC=N21,C_I2C_SDA_LOC=M21}" *)

module sys_mon


          (
          daddr_in,            // Address bus for the dynamic reconfiguration port
          dclk_in,             // Clock input for the dynamic reconfiguration port
          den_in,              // Enable Signal for the dynamic reconfiguration port
          di_in,               // Input data bus for the dynamic reconfiguration port
          dwe_in,              // Write Enable for the dynamic reconfiguration port
          reset_in,            // Reset signal for the System Monitor control logic
          busy_out,            // ADC Busy signal
          channel_out,         // Channel Selection Outputs
          do_out,              // Output data bus for dynamic reconfiguration port
          drdy_out,            // Data ready signal for the dynamic reconfiguration port
          eoc_out,             // End of Conversion Signal
          eos_out,             // End of Sequence Signal
          alarm_out);

          input [7:0] daddr_in;
          input dclk_in;
          input den_in;
          input [15:0] di_in;
          input dwe_in;
          input reset_in;
          output busy_out;
          output [5:0] channel_out;
          output [15:0] do_out;
          output drdy_out;
          output eoc_out;
          output eos_out;
          output alarm_out;

sys_mon_sysmon
inst (
      .daddr_in(daddr_in),
      .dclk_in(dclk_in),
      .den_in(den_in),
      .di_in(di_in),
      .dwe_in(dwe_in),
      .reset_in(reset_in),
      .vp (),
      .vn (),
      .busy_out(busy_out),
      .channel_out(channel_out),
      .do_out(do_out[15:0]),
      .drdy_out(drdy_out),
      .eoc_out(eoc_out),
      .eos_out(eos_out),
      .alarm_out(alarm_out)
      );


endmodule
