`timescale 1ps/1ps
module rtds_ddr4_mig (
  output wire c0_init_calib_complete,
  output wire dbg_clk,
  input wire c0_sys_clk_i,
  output wire [511 : 0] dbg_bus,
  output wire [16 : 0] c0_ddr4_adr,
  output wire [1 : 0] c0_ddr4_ba,
  output wire [0 : 0] c0_ddr4_cke,
  output wire [0 : 0] c0_ddr4_cs_n,
  inout wire [7 : 0] c0_ddr4_dm_dbi_n,
  inout wire [63 : 0] c0_ddr4_dq,
  inout wire [7 : 0] c0_ddr4_dqs_c,
  inout wire [7 : 0] c0_ddr4_dqs_t,
  output wire [0 : 0] c0_ddr4_odt,
  output wire [0 : 0] c0_ddr4_bg,
  output wire c0_ddr4_reset_n,
  output wire c0_ddr4_act_n,
  output wire [0 : 0] c0_ddr4_ck_c,
  output wire [0 : 0] c0_ddr4_ck_t,
  output wire c0_ddr4_ui_clk,
  output wire c0_ddr4_ui_clk_sync_rst,
  input wire c0_ddr4_aresetn,
  input wire [4 : 0] c0_ddr4_s_axi_awid,
  input wire [31 : 0] c0_ddr4_s_axi_awaddr,
  input wire [7 : 0] c0_ddr4_s_axi_awlen,
  input wire [2 : 0] c0_ddr4_s_axi_awsize,
  input wire [1 : 0] c0_ddr4_s_axi_awburst,
  input wire [0 : 0] c0_ddr4_s_axi_awlock,
  input wire [3 : 0] c0_ddr4_s_axi_awcache,
  input wire [2 : 0] c0_ddr4_s_axi_awprot,
  input wire [3 : 0] c0_ddr4_s_axi_awqos,
  input wire c0_ddr4_s_axi_awvalid,
  output wire c0_ddr4_s_axi_awready,
  input wire [63 : 0] c0_ddr4_s_axi_wdata,
  input wire [7 : 0] c0_ddr4_s_axi_wstrb,
  input wire c0_ddr4_s_axi_wlast,
  input wire c0_ddr4_s_axi_wvalid,
  output wire c0_ddr4_s_axi_wready,
  input wire c0_ddr4_s_axi_bready,
  output wire [4 : 0] c0_ddr4_s_axi_bid,
  output wire [1 : 0] c0_ddr4_s_axi_bresp,
  output wire c0_ddr4_s_axi_bvalid,
  input wire [4 : 0] c0_ddr4_s_axi_arid,
  input wire [31 : 0] c0_ddr4_s_axi_araddr,
  input wire [7 : 0] c0_ddr4_s_axi_arlen,
  input wire [2 : 0] c0_ddr4_s_axi_arsize,
  input wire [1 : 0] c0_ddr4_s_axi_arburst,
  input wire [0 : 0] c0_ddr4_s_axi_arlock,
  input wire [3 : 0] c0_ddr4_s_axi_arcache,
  input wire [2 : 0] c0_ddr4_s_axi_arprot,
  input wire [3 : 0] c0_ddr4_s_axi_arqos,
  input wire c0_ddr4_s_axi_arvalid,
  output wire c0_ddr4_s_axi_arready,
  input wire c0_ddr4_s_axi_rready,
  output wire c0_ddr4_s_axi_rlast,
  output wire c0_ddr4_s_axi_rvalid,
  output wire [1 : 0] c0_ddr4_s_axi_rresp,
  output wire [4 : 0] c0_ddr4_s_axi_rid,
  output wire [63 : 0] c0_ddr4_s_axi_rdata,
  input wire sys_rst
);
endmodule
