webtalk_init -webtalk_dir C:/project/RTDS/DDR/axi_ddr4_full_bist_2020_2/sim_work/xsim.dir/tb_smoke32/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Sep 15 15:23:26 2026" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "cc595c2f-0d8c-4e1a-88e3-a598ba8525c2" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "89d93c0a-5ebc-420a-b894-f0d84f2551f2" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "6" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i9-14900K" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3187 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "137.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key runtime -value "523865370 ps" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "40.81_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "13608_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1194227529 -regid "" -xml C:/project/RTDS/DDR/axi_ddr4_full_bist_2020_2/sim_work/xsim.dir/tb_smoke32/webtalk/usage_statistics_ext_xsim.xml -html C:/project/RTDS/DDR/axi_ddr4_full_bist_2020_2/sim_work/xsim.dir/tb_smoke32/webtalk/usage_statistics_ext_xsim.html -wdm C:/project/RTDS/DDR/axi_ddr4_full_bist_2020_2/sim_work/xsim.dir/tb_smoke32/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
